# Generated by Django 5.0.4 on 2024-05-15 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parentNeighborhood',
        ),
    ]
