# Generated by Django 5.0.4 on 2024-05-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_parentneighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployee',
            name='Financialactive',
        ),
    ]
