# Generated by Django 5.0.4 on 2024-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_address_alter_student_parentaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='parentUsername',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
