# Generated by Django 5.0.4 on 2024-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeAmount', models.FloatField()),
                ('schoolUniform', models.FloatField()),
                ('booksFee', models.FloatField()),
                ('transports', models.FloatField()),
                ('other', models.FloatField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('insertingTime', models.DateTimeField()),
                ('insertedUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear')),
            ],
            options={
                'unique_together': {('year', 'school_class', 'section', 'student', 'payID')},
            },
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('schoolFees', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('previousDebts', models.FloatField(blank=True, null=True)),
                ('exemptions', models.FloatField()),
                ('exemptionsDetail', models.TextField()),
                ('finalBalance', models.FloatField(blank=True, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear')),
            ],
            options={
                'unique_together': {('year', 'school_class', 'section', 'student')},
            },
        ),
    ]
