# Generated by Django 5.0.4 on 2024-05-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfees',
            name='description',
        ),
    ]
