# Generated by Django 5.0.4 on 2024-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourEvaluation',
            fields=[
                ('behaviourID', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('notes', models.TextField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear')),
            ],
            options={
                'unique_together': {('student', 'behaviourID', 'year', 'school_class', 'section')},
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('healthRecordID', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('parentsHaveBeenContacted', models.TextField()),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear')),
            ],
            options={
                'unique_together': {('student', 'healthRecordID', 'year', 'school_class', 'section')},
            },
        ),
    ]
