# Generated by Django 5.0.4 on 2024-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_behavioral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviourevaluation',
            name='notes',
            field=models.CharField(max_length=255),
        ),
    ]
