# Generated by Django 5.0.4 on 2024-05-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_behavioral', '0002_alter_behaviourevaluation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='parentsHaveBeenContacted',
            field=models.CharField(max_length=255),
        ),
    ]
