# Generated by Django 5.0.4 on 2024-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_ID', models.AutoField(primary_key=True, serialize=False)),
                ('city_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParentJob',
            fields=[
                ('parentjob_ID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religionID', models.AutoField(primary_key=True, serialize=False)),
                ('religionDesc', models.CharField(max_length=255)),
            ],
        ),
    ]
