# Generated by Django 5.0.4 on 2024-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dueDate', models.DateField()),
                ('fileInsert', models.FileField(blank=True, null=True, upload_to='assignments_inserted/')),
                ('fileSubmit', models.FileField(blank=True, null=True, upload_to='assignments_submit/')),
                ('link', models.URLField(blank=True, null=True)),
                ('assignmentGrade', models.FloatField(blank=True, null=True)),
                ('submit', models.BooleanField(default=False)),
                ('submit_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('excuse', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('insertingTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('classNameEnglish', models.CharField(max_length=255)),
                ('isActive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('examGrade', models.FloatField()),
                ('finalGrade', models.FloatField(default=None)),
                ('insertingTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gradeID', models.AutoField(primary_key=True, serialize=False)),
                ('firstQuarter', models.FloatField(blank=True, null=True)),
                ('secondQuarter', models.FloatField(blank=True, null=True)),
                ('firstSemester', models.FloatField(blank=True, null=True)),
                ('thirdQuarter', models.FloatField(blank=True, null=True)),
                ('fourthQuarter', models.FloatField(blank=True, null=True)),
                ('secondSemester', models.FloatField(blank=True, null=True)),
                ('finalAvg', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureID', models.AutoField(primary_key=True, serialize=False)),
                ('roomNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('yearID', models.AutoField(primary_key=True, serialize=False)),
                ('yearName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionID', models.IntegerField(unique=True)),
                ('sectionSymbol', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['sectionID'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subjectTextBook', models.CharField(max_length=255)),
            ],
        ),
    ]
