# Generated by Django 5.0.4 on 2024-04-27 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('times', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='insertedUserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='classID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.day'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='endTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.time'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='startTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='times.time'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='teacherID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.CreateModel(
            name='SchoolSittings',
            fields=[
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academic.studyyear')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='yearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='grade',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
        migrations.AddField(
            model_name='section',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.studyyear'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='sectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='grade',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='exam',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.section'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='subjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('year', 'school_class', 'section', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studentsubject',
            unique_together={('studentID', 'subjectID')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('year', 'school_class', 'section', 'student', 'subject', 'gradeID')},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('year', 'school_class', 'section', 'student', 'examID')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('subject', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('student', 'year', 'school_class', 'section', 'assignmentID')},
        ),
    ]
