# Generated by Django 5.0.4 on 2024-05-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentFinalGrade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
