# Generated by Django 5.0.4 on 2024-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_assignment_assignmentfinalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examGrade',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='finalGrade',
            field=models.FloatField(default=None, null=True),
        ),
    ]
