# Generated by Django 5.0.4 on 2024-05-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_exam_examgrade_alter_exam_finalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examGrade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='finalGrade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
