# Generated by Django 5.0.4 on 2024-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_exam_examgrade_alter_exam_finalgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='insertingTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
