# Generated by Django 5.0.4 on 2024-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_alter_exam_insertingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='linkInsert',
            field=models.URLField(blank=True, null=True),
        ),
    ]
