# Generated by Django 5.0.4 on 2024-06-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_rename_classnameenglish_class_classnameother'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='next_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_class', to='academic.class'),
        ),
    ]
