# Generated by Django 5.0.4 on 2024-06-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_class_next_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('subject', 'school_class', 'year')},
        ),
    ]
