# Generated by Django 5.0.4 on 2024-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
