# Generated by Django 5.0.4 on 2024-04-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('dayID', models.AutoField(primary_key=True, serialize=False)),
                ('dayName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('timeID', models.AutoField(primary_key=True, serialize=False)),
                ('hour', models.IntegerField()),
                ('minutes', models.IntegerField()),
            ],
        ),
    ]
